### ISSUE TITLE
`workflow buckets rm [BUCKET]` only removes 100 works

### ISSUE THREAD

**Issue by tjzegmott** [CHIMEFRB/workflow#120]
Should add an option to set the limit instead of only using the default of 100

**Comment by tjzegmott** [comment]
I think the issue comes from this call to `view()`: https://github.com/CHIMEFRB/workflow/blob/a3a1cabbb4ef54de07b7d50efcdeb3d7d18105d6/workflow/http/buckets.py#L174

**Comment by odarotto** [comment]
That's right, I can add a parameter to the command and pass it into the `view` call.
