### ISSUE TITLE
Pydantic version giving error

### ISSUE THREAD

**Issue by ketansand** [CHIMEFRB/workflow#74]
I was getting this error with an older version of pydantic

<img width="1439" alt="Screenshot 2024-06-28 at 6 33 49 PM" src="https://github.com/CHIMEFRB/workflow/assets/55292615/9a3e0f59-4635-4ea1-abe6-15b5f38eb324">

So I upgraded pydantic to a new version.

It resolved this issue 

But then --

Running workflow bucket in command line gives this error with the newest version of pydantic

<img width="1440" alt="Screenshot 2024-06-28 at 6 35 03 PM" src="https://github.com/CHIMEFRB/workflow/assets/55292615/a3a45460-686f-4c73-ab51-bc411164ebe3">

All this started when I upgraded my chime_frb_api to the newest version.

**Comment by ketansand** [comment]
The older pydantic version is 1.10.17
The newere pydantic version is 2.7.4

**Comment by shinybrar** [comment]
This is an expected error @ketansand since workflow is only Pydantic >=2.0 compatible. To see the full list of compatible dependencies see the project [pyproject.toml](https://github.com/CHIMEFRB/workflow/blob/main/pyproject.toml) file.
